### ISSUE TITLE
npm run serve ou npm run start

### ISSUE THREAD

**Issue by ouhouhsami** [MTES-MCT/camino-ui#1]
Bonjour @francoisromain 

est-ce que ce ne serait pas plutôt 
`npm run start` à la place de `npm run serve` dans le README ?

Merci

**Comment by francoisromain** [comment]
Oui, exact j'ai fait une erreur dans le readme c'est npm run start. 

Cependant, pour une utilisation locale en mode `dev`, en local, il faut faire `npm run dev` sur l'api et aussi `npm run dev` sur l'ui.

**Comment by francoisromain** [comment]
j'ai corrigé le readme
