### ISSUE TITLE
Fichiers .env

### ISSUE THREAD

**Issue by ouhouhsami** [MTES-MCT/camino-ui#3]
Hello @francoisromain 

alors, "en tant que nouvel arrivant sur le code", la partie https://github.com/MTES-MCT/camino-ui#configuration n'est pas immédiate à la compréhension, nous nous sommes perdu entre env de prod et de développement. 
Grâce à @guillaumelevieux une base de test fonctionne avec un point .env suivant : 
```
NODE_PORT=8080
VUE_APP_API_URL=http://localhost:4000
```
et à la suite d'avoir lancé : 
`npm run dev`

Comment clarifier la doc en conséquence ?

merci !

**Comment by francoisromain** [comment]
Hello Samuel, effectivement j'avais oublié de documenter les fichier `.env.development` et `.env.production`. J'ai mis à jour la doc hier soir pour y remédier. Dis moi si cela te semble clair. merci

**Comment by ouhouhsami** [comment]
oui, c'est plus clair, 

je pense maintenant que la suite de la précision du readme se trouve dans mon autre issue : https://github.com/MTES-MCT/camino-ui/issues/4
