### ISSUE TITLE
Reload sur server

### ISSUE THREAD

**Issue by ouhouhsami** [MTES-MCT/camino-ui#4]
Rebonjour, 

est-ce qu'il y a une "ligne de conduite" pour comprendre "comment et quand" sont regénérés ("buildés") les fichiers js, fichiers .env etc. pendant le processus de développement. 
Autrement dit, lorsque l'on modifie les fichiers, quand doit-on ou pas relancer `npm run dev`.

Merci !

**Comment by francoisromain** [comment]
le processus de build sont gérés par vue-cli (qui utilise webpack). La doc qui explique précisemment comment cela fonctionne est ici: https://cli.vuejs.org/. Les nommage des fichier `.env`, `.env.development` et `.env.production`, ainsi que de la variable `VUE_APP_API_URL` respecte les conventions de vue-cli (voir ici: https://cli.vuejs.org/guide/mode-and-env.html#modes)

En résumé: 
- `.env` contient les variables d'environnement qui sont utilisé en prod et en dev
- `.env.development` et `.env.production` contiennent les variables d'environnement spécifiques. 
- les variables d'environnement sont utilisé par webpack au moment du build (et, en dev, elles ne sont pas rechargées par webpack-dev-server si elles sont modifiées après coup. Il faut donc relancer `npm run dev` si une variable `.env.…` est modifiée)
- une dernière précision: webpack-dev-server (qui est utilisé par `npm run dev`) n'écrit pas de fichiers sur le disque dur. Tout est géré en mémoire avec un proxy.

**Comment by francoisromain** [comment]
je proose : 
- d'ajouter une ligne de commentaire dans chacun des fichier `.env` pour expliciter les variables
- de mettre un lien depuis le readme vers la doc vue-cli (https://cli.vuejs.org/guide/mode-and-env.html#modes ) pour plus d'informations sur le fonctionnement de ces variables. 

qu'en penses tu ?

**Comment by ouhouhsami** [comment]
Go si ça te semble mieux. Faut qu'on trouve un autre dev pour qu'il tente l'installation !

**Comment by francoisromain** [comment]
voir ici:

**Comment by francoisromain** [comment]
voir ici: 
- https://github.com/MTES-MCT/camino-ui/blob/365758033d4e8513d0fd47a57fc0e28eab16b608/.env.development-example#L1
- https://github.com/MTES-MCT/camino-ui/blob/365758033d4e8513d0fd47a57fc0e28eab16b608/.env.production-example#L1
- https://github.com/MTES-MCT/camino-ui/blob/4c78fe1ae723f0b66340fee65bd737fbb9e3031d/.env.example#L1
- https://github.com/MTES-MCT/camino-ui/blob/master/readme.md
